---
# Authentication for Kerberos-based Realms
:keytab_path: /etc/foreman-proxy/freeipa.keytab
:principal: realm-proxy@{{ foreman_config.foreman_env.domain }}

:ipa_config: /etc/ipa/default.conf
# Remove from DNS when deleting the FreeIPA entry
:remove_dns: true

# verify IPA API HTTPS server certificate
:verify_ca: true
