---
:settings_directory: "/etc/foreman-proxy/settings.d"
:ssl_ca_file: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
:ssl_certificate: "/etc/puppetlabs/puppet/ssl/certs/foreman-master.{{ foreman_config.foreman_env.domain }}.pem"
:ssl_private_key: "/etc/puppetlabs/puppet/ssl/private_keys/foreman-master.{{ foreman_config.foreman_env.domain }}.pem"
:trusted_hosts:
- foreman-master.{{ foreman_config.foreman_env.domain }}
:foreman_url: https://foreman-master.{{ foreman_config.foreman_env.domain }}
:bind_host: "*"
:https_port: 8443
:log_file: "/var/log/foreman-proxy/proxy.log"
:log_level: INFO
:log_buffer: 2000
:log_buffer_errors: 1000
